name: Package MCPACK HideMySeed

on:
  # Runs on pushes targeting the default branch
  # push:
  #   branches:
  #     - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Update World Section UI
        run: python scripts/clean.py
      - name: Package MCPACK
        run: python scripts/package.py 
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: HideMySeed
          path: |
            HideMySeed.mcpack
            README.md
          if-no-files-found: error